sonar.projectKey=rgkim-hsu_Smart-IoT-Planting-System
sonar.organization=rgkim-hsu
sonar.projectName=Smart IoT Planting System
sonar.projectVersion=1.0

# 전체 분석
sonar.sources=.

# 공통 제외
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.git/**,**/__pycache__/**,**/venv/**,**/*.pyc,**/migrations/**,**/tests/**,**/static/**,**/media/**

# Python
sonar.python.version=3.7,3.8,3.9,3.10
